### PR TITLE
Implement Ihelper and IServicesMgr

### PR DESCRIPTION
**Pull request by mrobustelli**
There are a few changes here.  @ppande1020 let me know when you have time and we can review.

### CODE REVIEW

**Comment by dvbarnes** [comment]
Any way we can get this into the nuget? I would really like to use this.

**Comment by mrobustelli** [comment]
@dvbarnes The original package is available in a nuget.  With Fest we were unable to review this pull request, we were unable to review it yet.  We should do that shortly.  Search for RelativityTestHelpersNuget in the nuget Package Manger.  Please note, the pull request this thread is on revolves around the type of eventhandler.  We are going to try and get it to implement the IHelper interface.

**Comment by dvbarnes** [comment]
I have the nuget package, I'm just hoping we can get this PR in so that I can take advantage of the changes that have been made in this PR specifically.

**Comment by ppande1020** [comment]
Hey David. I am working on merging this change and will get it to you as soon as possible. Thanks!

**Comment by ppande1020** [comment]
The changes have been merged and the new NuGet package has been created. Please find RelativityTestHelpersNuget v1.2 in your NuGet gallery. I plan to test out this nugget package tomorrow but if you see any issues using this before I get to it, just ping me. Thanks!

https://www.nuget.org/packages/RelativityTestHelpersNuget/

**Pull request merged**
