### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by mrobustelli**

### CODE REVIEW

**Comment by dvbarnes** [comment]
Along these lines, should we start working on a CONTRIBUTING file as well? I know I've kinda been just going crazy with these changes but I think we should start outlining what it means to contribute to this project.

**Comment by mrobustelli** [comment]
Working on that now!

**Comment by mrobustelli** [comment]
@dvbarnes Can you review this and merge it if it is cool with you.  Would love to get your take on it.  Still working on the Contributing, will include that in separate request.

**Comment by dvbarnes** [comment]
seems standard, didn't know I had review rights

**Pull request merged**
